name: beer_store
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  go_router: ^6.5.1
  dio: ^5.1.0
  injectable: ^2.1.1
  google_fonts: ^4.0.3
  font_awesome_flutter: ^10.4.0
  palette_generator: ^0.3.3+2
  device_frame: ^1.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.5
  build_runner: ^2.3.3

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
